---
title: Mission, Vision, <br\> and Core Values
author: "UniSA MS Group at FII"
output: 
  ioslides_presentation:
    css: style.css
---


## Work-in-Progress: Overview

Ultimately we want to arrive at Mission and Vision Statements, as well as core 
values/ attributes for our MS group here at FII. What follow are some guideline 
slides describing some of the guiding questions we will use to arrive at these, 
and places to hold the ideas we come up with during brainstorming. 

Following these slides will be three sections, titled "Mission Statement", 
"Vision Statement", and "Core Values", which will be where we store the final 
product. When we are done brainstorming and get closer to the final product we 
can reduce or even remove this slide and the following Work-in-Progress/ 
brainstorming sections.

## Work-in-Progress: Hedgehog

We will use the three questions:

1. What Drives Us?
2. Unique Strengths?
3. Current Known Economic Potential

to find the intersection between these three that will inform our brainstorming.

## Brainstorming: 1.

1.: What Drives Us? (What do we want to be the best in the world at? What we 
   *cannot* be the best in the world at?)

- Being able to link/bridge different
  fields and disciplines
- We should be the best at addressing the challenges of our time for MS
application in Proteomics
-We should aimto be the leaders in MSI and tissue-based proteomics in Australia
and South-East Asia
- Being role models/leaders/pioneers in rigorous reporting and interpretation of 
  experimental analyses/workflows/processes
- Influencing other groups to aspire to do the same
- Defining practical implementation
- A constant refinement/adaptation of these principles
- Providing platform and structure to ensure that any person coming into the lab/group 
  will be taught to achieve a "world-class standard”
  
## Brainstorming: 1.

- Exhibit a Willingness to learn
- Exhibit a Willingness to teach
- Implement time management and stage-gate principles
- Achieve Work/life balance
- Implement and adhere to 5S principles
- A culture that rewards the observation, reporting and addressing of challenges (e.g. recognising 
  problems/errors/need for improvements etc.)
- A solutions and outcome focused approach to dealing with problems/errors/
needs for improvements etc.
- A drive to take our current weaknesses and make them our strengths

## Brainstorming: 2. Strengths

2: What are our Unique Strengths (and weaknesses)?: 

Strengths:

- Enthusiasm
- Robustness and consistency (integrity)
- Adherence to the Australian Code for Responsible Conduct of Research
- Access to FII infrastructure, and the FII accelerator grants
- MS Imaging Expertise
- MALDI Biotyper
- MALDI-TOF/TOF Expertise
- Laser micro-dissection coupled with MSI

## Brainstorming: 2. Strengths

- Hardware access (open access to hardware through FII)
- New group – opportunity to create a culture that aligns with our values
- Modern approach – openness
- Complimentary strengths and weaknessed amongst people in the group.
- International connections in the field of Proteomics - such as having direct
access to the HUPO committee
- Direct and exclusive access to gynecological cancers tissue samples as well
as clinical expertise

## Brainstorming: 2. Weakness

2: What are our Unique Strengths (and weaknesses)?: 

Weaknesses:

- Small group: FTE (limited in resources)
- Hardware access (limited number and stable configurations: 2x MALDI-TOF, 1x QqQ, shared 2x Qq-TOF)
- New group – time required for lab/process setup
- Limited expertise in LC-MSMS, particularly for small molecules
- Enthusiasm: capacity limitations, time management
    - Learning to say no (knowing capacity)
    - Work/life balance

## Brainstorming: 3. 

3: Current Known Economic Potential?: 

- Publications
    - Data in Briefs
- Industry Collaboration
    - CSL
    - Bionomics
    - Coopers
    - Ziltek
    - Agilent
    - Bruker
    - Other...
    - Future Collaborations
    - NCRIS, Current
    - OCRF, Current
    - FIA, Current

## Brainstorming: 3. 

3: Current Known Economic Potential?: 

- Active pursuit of non-federal funding (e.g. State funding)
    - Defence
    - Food
    - All post-doc group members expected to be pro-active in defining and 
    applying for grant funding


## Mission Statement
**Our Mission Statement:**

fiiMS is a centre of expertise for biological Mass Spectrometry analyses. 
We set the benchmark for global best practice in the preparation, analysis and 
reporting of results.
We undertake both fundamental and applied research to acheive tangible outcomes 
which can be provided to industrial partners with the highest scientific 
standards of transparency and reproducibility.



## Vision Statement

**Our Vision Statement:**

We aim to develop a culture that instills:
- collaboration, communication, enthusiasm and drive for excellence
amongst all members and affiliates of fiiMS.
- the concepts of free trade of information, sound experimental design and lab 
practice by standardising our approach to analysis and reporting of data and 
allowing it to evolve and improve over time.

This culture will guide our continuing development of our world-leading 
expertise in the use of MS for imaging and 'omics' approaches.

## Core Values

Our values should align with the University's (see following slides) as best as 
possible but cover all important aspects of our day-to-day operations:

- **Integrity:** We adhere to best practices including the 
  [Australian Code for the Responsible Conduct of Research](https://www.nhmrc.gov.au/guidelines-publications/r39).
- **Principle:** We value, adhere to and teach the scientific method with particular emphasis on  transparency, reproducibility and fundamental concept that ``the only test of the validity of an idea is experiement'' (Richard Feynman).
- **Collaboration:** We believe that a collaborative approach is key to
addressing the needs of industry as well as fundamental research. We aim to lead 
by example through defining, implementing and fostering successful 
collaborations.



## Core Values

- **Innovation:** We will be leaders in Mass Spectrometry based techniques, 
driven by state-of-the art technology, good scientific practice, and solving 
current challenges in the field.
- **Openness:** We strive to culture an environment in which people feel comfortable and encouraged to give and receive constructive criticism.



## UniSA Values and Attributes

What follow are several slides outlining the UniSA Core Values and Attributes,
for reference. Ultimately when we are done defining our Core Values and 
Attributes and are satisfied with how they fit with those of the university, we 
can remove this slide forward, leaving a document just describing our values, or
we could replace and/ or add a discussion of how our values/ attributes fit with 
those of the university here.

## UniSA Core Values

UniSA defines values that every affiliated employee should aspire to achieve:

- **Scholarship:** UniSA promotes and sustains open intellectual enquiry 
  characterised by high standards of ethics and integrity. academic rigour, 
  excellence and relevance underpin our actions in research and its application, 
  in teaching and learning and in engagement with our communities.
- **Engagement:** UniSA’s teaching and research connect strongly with the issues
  of our local, national and international stakeholders --— students, alumni, 
  staff, partners, professions, government, industry, academic peers and 
  community groups.
  
## UniSA Core Values

- **Social Justice:** UniSA gives effect to reconciliation with indigenous 
  Australians and builds social cohesion by achieving equitable educational 
  access and outcomes across our diverse student community, through research 
  that aims to improve the quality of life and by acting responsibly as a 
  corporate citizen.
- **Sustainability:** UniSA contributes to environmentally, economically,
  socially and culturally sustainable development, and we work on reducing our 
  own environmental impact.
- **Innovation:** UniSA anticipates change and acts quickly to seize
  opportunities and solve problems.
- **Openness:** UniSA is outward looking, welcoming diversity and the wide range
  of perspectives it brings, international in outlook, collaborative, creative, 
  agile and enterprising.
  
## UniSA Core Attributes

To exemplify the essence and culture of an enterprise workforce, we aspire that
each of our staff will:

- Be trusted, authentic and self-aware
- Take the initiave and deliver results
- Provide solutions
- Communicate with impact
- Lead and work well with others.

See the 
[UniSA Website](http://w3.unisa.edu.au/staffdev/resources/core_attributes.asp).

  



